[package]
name = "MNIST_GPU"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
futures = "0.3.31"
bytemuck = { version = "1.20.0", features = ["derive"] }
flume = "0.11.1"
env_logger = "0.11.5"
pollster = "0.4.0"
rand = "0.8.5"